import { Injector } from "../di-container/di-container-injector";
import { PASSWORD_SERVICE } from "./interfaces/password-service.interface";
import { TOKEN_SERVICE } from "./interfaces/token-service.interface";
import { LOGIN_USE_CASE } from "./interfaces/auth/login.use-case.interface";
import { LOGOUT_USE_CASE } from "./interfaces/auth/logout.use-case.interface";
import { ME_USE_CASE } from "./interfaces/auth/me.use-case.interface";
import { REFRESH_USE_CASE } from "./interfaces/auth/refresh.use-case.interface";
import { REGISTER_USE_CASE } from "./interfaces/auth/register.use-case.interface";
import { CONTEXT_REPOSITORY } from "../domain/interfaces/context-repository.interface";
import { PROJECT_REPOSITORY } from "../domain/interfaces/project-repository.interface";
import { REFRESH_TOKEN_REPOSITORY } from "../domain/interfaces/refresh-token-repository.interface";
import { TASK_REPOSITORY } from "../domain/interfaces/task-repository.interface";
import { USER_REPOSITORY } from "../domain/interfaces/user-repository.interface";
import { LoginUseCase } from "./use-cases/auth/login.use-case";
import { LogoutUseCase } from "./use-cases/auth/logout.use-case";
import { MeUseCase } from "./use-cases/auth/me.use-case";
import { RefreshUseCase } from "./use-cases/auth/refresh.use-case";
import { RegisterUseCase } from "./use-cases/auth/register.use-case";
import { CREATE_CONTEXT_USE_CASE } from "./interfaces/context/create-context.use-case.interface";
import { CREATE_PROJECT_USE_CASE } from "./interfaces/project/create-project.use-case.interface";
import { COMPLETE_TASK_USE_CASE } from "./interfaces/task/complete-task.use-case.interface";
import { CREATE_TASK_USE_CASE } from "./interfaces/task/create-task.use-case.interface";
import { DELETE_CONTEXT_USE_CASE } from "./interfaces/context/delete-context.use-case.interface";
import { DELETE_PROJECT_USE_CASE } from "./interfaces/project/delete-project.use-case.interface";
import { DELETE_TASK_USE_CASE } from "./interfaces/task/delete-task.use-case.interface";
import { GET_CONTEXT_USE_CASE } from "./interfaces/context/get-context.use-case.interface";
import { GET_PROJECT_USE_CASE } from "./interfaces/project/get-project.use-case.interface";
import { GET_TASK_USE_CASE } from "./interfaces/task/get-task.use-case.interface";
import { LIST_CONTEXTS_USE_CASE } from "./interfaces/context/list-contexts.use-case.interface";
import { LIST_PROJECTS_USE_CASE } from "./interfaces/project/list-projects.use-case.interface";
import { LIST_TASKS_USE_CASE } from "./interfaces/task/list-tasks.use-case.interface";
import { UPDATE_CONTEXT_USE_CASE } from "./interfaces/context/update-context.use-case.interface";
import { UPDATE_PROJECT_USE_CASE } from "./interfaces/project/update-project.use-case.interface";
import { REOPEN_TASK_USE_CASE } from "./interfaces/task/reopen-task.use-case.interface";
import { UPDATE_TASK_USE_CASE } from "./interfaces/task/update-task.use-case.interface";
import { CreateContextUseCase } from "./use-cases/context/create-context.use-case";
import { CreateProjectUseCase } from "./use-cases/project/create-project.use-case";
import { CompleteTaskUseCase } from "./use-cases/task/complete-task.use-case";
import { CreateTaskUseCase } from "./use-cases/task/create-task.use-case";
import { DeleteContextUseCase } from "./use-cases/context/delete-context.use-case";
import { DeleteProjectUseCase } from "./use-cases/project/delete-project.use-case";
import { DeleteTaskUseCase } from "./use-cases/task/delete-task.use-case";
import { GetContextUseCase } from "./use-cases/context/get-context.use-case";
import { GetProjectUseCase } from "./use-cases/project/get-project.use-case";
import { GetTaskUseCase } from "./use-cases/task/get-task.use-case";
import { ListContextsUseCase } from "./use-cases/context/list-contexts.use-case";
import { ListProjectsUseCase } from "./use-cases/project/list-projects.use-case";
import { ListTasksUseCase } from "./use-cases/task/list-tasks.use-case";
import { UpdateContextUseCase } from "./use-cases/context/update-context.use-case";
import { UpdateProjectUseCase } from "./use-cases/project/update-project.use-case";
import { ReopenTaskUseCase } from "./use-cases/task/reopen-task.use-case";
import { UpdateTaskUseCase } from "./use-cases/task/update-task.use-case";

export const injectApplication: Injector = async (container, env) => {
  const tasks = container.resolve(TASK_REPOSITORY);
  const contexts = container.resolve(CONTEXT_REPOSITORY);
  const projects = container.resolve(PROJECT_REPOSITORY);
  const users = container.resolve(USER_REPOSITORY);
  const refreshTokenRepo = container.resolve(REFRESH_TOKEN_REPOSITORY);
  const tokenService = container.resolve(TOKEN_SERVICE);
  const passwordService = container.resolve(PASSWORD_SERVICE);
  // Auth
  container.bind(REGISTER_USE_CASE, new RegisterUseCase(users, passwordService, tokenService, refreshTokenRepo));
  container.bind(LOGIN_USE_CASE, new LoginUseCase(users, passwordService, tokenService, refreshTokenRepo));
  container.bind(REFRESH_USE_CASE, new RefreshUseCase(users, tokenService, refreshTokenRepo));
  container.bind(ME_USE_CASE, new MeUseCase(users));
  container.bind(LOGOUT_USE_CASE, new LogoutUseCase(refreshTokenRepo, tokenService));
  // Task
  container.bind(CREATE_TASK_USE_CASE, new CreateTaskUseCase(tasks, contexts, projects));
  container.bind(GET_TASK_USE_CASE, new GetTaskUseCase(tasks));
  container.bind(LIST_TASKS_USE_CASE, new ListTasksUseCase(tasks));
  container.bind(UPDATE_TASK_USE_CASE, new UpdateTaskUseCase(tasks, contexts, projects));
  container.bind(DELETE_TASK_USE_CASE, new DeleteTaskUseCase(tasks));
  container.bind(COMPLETE_TASK_USE_CASE, new CompleteTaskUseCase(tasks));
  container.bind(REOPEN_TASK_USE_CASE, new ReopenTaskUseCase(tasks));
  // Project
  container.bind(CREATE_PROJECT_USE_CASE, new CreateProjectUseCase(projects));
  container.bind(GET_PROJECT_USE_CASE, new GetProjectUseCase(projects));
  container.bind(LIST_PROJECTS_USE_CASE, new ListProjectsUseCase(projects));
  container.bind(UPDATE_PROJECT_USE_CASE, new UpdateProjectUseCase(projects));
  container.bind(DELETE_PROJECT_USE_CASE, new DeleteProjectUseCase(projects, tasks));
  // Context
  container.bind(CREATE_CONTEXT_USE_CASE, new CreateContextUseCase(contexts));
  container.bind(GET_CONTEXT_USE_CASE, new GetContextUseCase(contexts));
  container.bind(LIST_CONTEXTS_USE_CASE, new ListContextsUseCase(contexts));
  container.bind(UPDATE_CONTEXT_USE_CASE, new UpdateContextUseCase(contexts));
  container.bind(DELETE_CONTEXT_USE_CASE, new DeleteContextUseCase(contexts, tasks));
  return container;
};
