export enum CapturedItemStatus {
  INBOX = 'INBOX',
  CLARIFIED_AS_ACTION = 'CLARIFIED_AS_ACTION',
  CLARIFIED_AS_PROJECT = 'CLARIFIED_AS_PROJECT',
  REFERENCE = 'REFERENCE',
  SOMEDAY = 'SOMEDAY',
  TRASH = 'TRASH',
}
